<a href="https://colab.research.google.com/github/kkobug222/python/blob/main/30821_%EC%A0%95%EC%A7%80%EC%9B%90_jh_%EB%94%A5%EB%9F%AC%EB%8B%9D(188_198)_%EB%B0%B0%EB%B6%80%EC%9A%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Ⅳ-1-2 퍼셉트론
### 퍼셉트론으로 AND, OR, NOT, XOR 연산 구현하기

1. 라이브러리를 불러온다.

In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import mse

## AND 연산

2. 데이터를 입력하여 AND 연산을 구현해 보고 결과를 확인한다.

In [ ]:
tf.random.set_seed(807) # 시드를 배정합니다.

# 데이터 준비하기                      A   B
data = np.array([[0, 0],          ##   0   0
                 [0, 1],          ##   0   1
                 [1, 0],          ##   1   0
                 [1, 1]])         ##   1   1
                                  ##   S
output = np.array([[0],           ##   0
                  [0],            ##   0
                  [0],            ##   0
                  [1]])           ##   1

3. 단층 퍼셉트론 모델을 구성한다.

In [ ]:
# 모델 구성하기 # 단층 퍼셉트론을 구성합니다
model = Sequential() #딥러닝 만드는 기본구조
model.add(Dense(1, input_shape = (2, ) , activation = 'linear')) #(2, ):2개씩 들어감., activation 활성화 함수

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
# 모델 준비하기
model.compile(optimizer = SGD(), loss = mse, metrics = ['acc']) #optimizer 최적화 , loss 손실함수

4. 학습을 실행한다.

In [ ]:
# 에폭은 약 500번 정도
model.fit(data, output, epochs = 500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 591ms/step - acc: 0.7500 - loss: 1.4591
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - acc: 0.7500 - loss: 1.3988
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7500 - loss: 1.3421
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7500 - loss: 1.2888
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7500 - loss: 1.2385
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7500 - loss: 1.1912
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - acc: 0.7500 - loss: 1.1467
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7500 - loss: 1.1047
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - acc: 0.7500 - loss: 1.0652
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7500 - loss: 1.0279
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7500 - loss: 0.9928
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7500 - loss: 0.9596
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/st

5. 가중치와 바이어스 확인하고 결과를 적는다.

In [ ]:
# 가중치와 바이어스를 확인합니다.
model.get_weights()

[array([[0.4121955],
        [0.2989327]], dtype=float32),
 array([-0.07867885], dtype=float32)]

6. 데이터를 직접 입력하여 활성화 함수의 기준점을 짐작해 보고 결과를 해석한다.

In [ ]:
k = model.predict(np.array([[int(input("입력 : ")) for j in range(2)] for i in range(1)]))
k

입력 : 1
입력 : 1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([[0.6324494]], dtype=float32)

7. OR, NOT, XOR 데이터를 입력한 다음 기준점을 생각해 보고 결과를 해석하여 적
는다.

## OR 연산

In [ ]:
# OR 연산
tf.random.set_seed(807) # 시드를 배정합니다.

# 데이터 준비하기
data = np.array([[0, 0],
                 [0, 1],
                 [1, 0],
                 [1, 1]])
output = np.array([[0],           ##   0
                  [1],            ##   1
                  [1],            ##   1
                  [1]])           ##   1

In [ ]:
# 모델 구성하기    # 단층 퍼셉트론을 구성합니다
model = Sequential()
model.add(Dense(1, input_shape = (2, ) , activation = 'linear'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
# 모델 준비하기
model.compile(optimizer = SGD(), loss = mse, metrics = ['acc'])

In [ ]:
# 학습시키기
model.fit(data, output, epochs = 500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 625ms/step - acc: 0.5000 - loss: 0.4289
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - acc: 0.5000 - loss: 0.4083
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - acc: 0.5000 - loss: 0.3890
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - acc: 0.7500 - loss: 0.3709
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - acc: 0.7500 - loss: 0.3538
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - acc: 0.7500 - loss: 0.3378
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - acc: 0.7500 - loss: 0.3228
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - acc: 0.7500 - loss: 0.3088
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - acc: 0.7500 - loss: 0.2955
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - acc: 0.7500 - loss: 0.2831
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - acc: 0.7500 - loss: 0.2715
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - acc: 0.7500 - loss: 0.2605
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/s

In [ ]:
# 가중치와 바이어스를 확인합니다.
model.get_weights()

[array([[0.5069975 ],
        [0.46000412]], dtype=float32),
 array([0.2695703], dtype=float32)]

In [ ]:
# 데이터 넣어서 확인하기
k = model.predict(np.array([[int(input("입력 : ")) for j in range(2)] for i in range(1)]))
k

입력 : 1
입력 : 0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([[0.7765678]], dtype=float32)

# NOT연산

In [ ]:
# NOT 연산
tf.random.set_seed(807) # 시드를 배정합니다.

# 데이터 준비하기
data = np.array([[0],
                 [1]])
output = np.array([[1],           ##   0
                  [0]])           ##   1

In [ ]:
# 모델 구성하기      # 단층 퍼셉트론을 구성합니다
model = Sequential()
model.add(Dense(1, input_shape = (1, ) , activation = 'linear'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
# 모델 준비하기
model.compile(optimizer = SGD(), loss = mse, metrics = ['acc'])

In [ ]:
# 학습시키기
model.fit(data, output, epochs = 500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 429ms/step - acc: 0.0000e+00 - loss: 0.7864
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.0000e+00 - loss: 0.7801
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - acc: 0.0000e+00 - loss: 0.7739
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - acc: 0.0000e+00 - loss: 0.7677
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.0000e+00 - loss: 0.7616
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.0000e+00 - loss: 0.7555
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - acc: 0.0000e+00 - loss: 0.7495
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - acc: 0.0000e+00 - loss: 0.7436
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.0000e+00 - loss: 0.7377
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - acc: 0.0000e+00 - loss: 0.7319
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.0000e+00 - loss: 0.7261
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.0000e+00 - loss: 0.7204


In [ ]:
# 가중치와 바이어스를 확인합니다.
model.get_

In [ ]:
# 데이터 넣어서 확인하기
k = model.predict(np.array([[int(input("입력 : ")) for j in range(1)] for i in range(1)]))
k

# 4. XOR연산

In [ ]:
# XOR 연산
tf.random.set_seed(807) # 시드를 배정합니다.

# 데이터 준비하기
data = np.array([[0, 0],
                 [0, 1],
                 [1, 0],
                 [1, 1]])
output = np.array([[0],           ##   0
                  [1],            ##   1
                  [1],            ##   1
                  [0]])           ##   0

In [ ]:
# 모델 구성하기    # 단층 퍼셉트론을 구성합니다
model = Sequential()
model.add(Dense(30, input_shape = (2, ) , activation = 'relu'))
model.add(Dense(20, activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(1, activation = 'relu'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
# 모델 준비하기
model.compile(optimizer = SGD(), loss = mse, metrics = ['acc'])

In [ ]:
# 학습시키기
model.fit(data, output, epochs = 500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - acc: 0.5000 - loss: 0.3927
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 470ms/step - acc: 0.5000 - loss: 0.3808
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.5000 - loss: 0.3696
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.5000 - loss: 0.3583
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - acc: 0.5000 - loss: 0.3477
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.5000 - loss: 0.3379
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.5000 - loss: 0.3287
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.5000 - loss: 0.3201
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - acc: 0.5000 - loss: 0.3121
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.5000 - loss: 0.3045
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.5000 - loss: 0.2975
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.5000 - loss: 0.2908
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step

In [ ]:
# 가중치와 바이어스를 확인합니다.
model.get_weights()

[array([[ 0.5105526 , -0.04779887, -0.32225165, -0.05341393,  0.28731644,
          0.25098908, -0.12769899, -0.09641608, -0.19161046,  0.11933574,
         -0.24902909,  0.03435808, -0.32541126, -0.2774738 ,  0.3731861 ,
          0.29583347,  0.14341623, -0.06354812,  0.3917192 ,  0.07976839,
         -0.06331334,  0.5072152 ,  0.10955148,  0.3759799 ,  0.04730121,
          0.4301302 , -0.1236709 , -0.05971673, -0.02734276, -0.13539627],
        [-0.07247552,  0.37432122, -0.37585092, -0.07006925,  0.18589985,
          0.06612987,  0.30174074,  0.42306262,  0.19155471, -0.30209294,
         -0.1140247 ,  0.28415045,  0.42231783,  0.28643987,  0.32372186,
         -0.027464  ,  0.20416255, -0.16966385, -0.3922885 , -0.18637244,
         -0.07726622, -0.12966958,  0.36975783, -0.1537981 ,  0.24431941,
          0.2927863 ,  0.51143825, -0.17065296,  0.17731914,  0.11716432]],
       dtype=float32),
 array([ 6.1891720e-02,  4.8161421e-02,  0.0000000e+00,  0.0000000e+00,
        -9.903

In [ ]:
# 데이터 넣어서 확인하기
k = model.predict(np.array([[int(input("입력 : ")) for j in range(2)] for i in range(1)]))
k
# 단일 퍼셉트론으론 XOR 연산을 구분할 수 없다.

입력 : 0
입력 : 1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([[0.95956486]], dtype=float32)